services:
  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:v2.55.0
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.2.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml

  tempo:
    image: grafana/tempo:2.6.1
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./otel-collector/otel-collector.yml:/etc/otel-collector.yml
    depends_on:
      - loki
      - tempo

volumes:
  grafana_data: